<a href="https://colab.research.google.com/github/Pilipchak/testexam/blob/master/task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Общий код для считывания данных



In [ ]:
import numpy as np

In [ ]:
def read_matrix(path):
    with open(path, 'r') as file:
        n = int(file.readline())
        matrix = np.zeros((n, n), dtype=int)
        for i in range(n):
            matrix[i] = list(map(int, file.readline().split()))
        return matrix

In [ ]:
def read_matrix_f(path):
    with open(path, 'r') as file:
        n = int(file.readline())
        matrix = np.array(list(map(int, file.readline().split()))).reshape((n, n))
        return matrix

In [ ]:
def read_vector(path):
   with open(path, 'r') as file:
        n = int(file.readline())
        vector = np.array(list(map(int, file.readline().split())))
        return vector

In [ ]:
A = read_matrix("input.txt")
b = read_vector("vector.txt")

B = read_matrix("basis.txt")

## Задача 1

In [ ]:
np.linalg.det(A)

-4.0

## Задача 2


In [ ]:
np.trace(A)

3

## Задача 3


In [ ]:
inv = np.linalg.solve(A, np.eye(A.shape[0]))
inv @ inv @ inv

array([[-1.      ,  0.      ],
       [ 0.      ,  0.015625]])


## Задача 4


In [ ]:
np.linalg.inv(B) @ A @ B

array([[-1.,  0.],
       [ 0.,  4.]])

## Задача 5


In [ ]:
np.linalg.solve(A, np.eye(A.shape[0])) @ b

array([-1.  ,  0.25])

## Задача 6



In [ ]:
sum(np.linalg.eig(A)[0])

3.0

## Задача 7


In [ ]:
max(abs(np.linalg.eig(A)[0]))

4.0

## Задача 8


In [82]:
val, vec = np.linalg.eig(A)
index = np.argsort(np.abs(val))[-2]
vec[index]

array([[1., 0.],
       [0., 1.]])